### ISSUE TITLE
Plotting two CRPs on the sns.facetgrid by list_type? 

### ISSUE THREAD

**Issue by jeon11** [mortonne/psifr-notebooks#1]
Hello Neal,

Thank you for this awesome toolbox and excellent examples. I've been recently converting the newest cdcat data to match with psifr-friendly data frames, and am able to plot various pretty graphs. 

One thing I had trouble was plotting the two CRPs in one grid (based on `list_type`). Currently, I can only plot one condition at a time and would be great to overlay the two conditions. I tried referring and modifying your `fr.plot_lag_crp` and `lag_crp` but then it involved messing with `transition` and thought to reach out to you. I think the code's especially tricky that it separately queries the negative and positive values for plotting. 

My current data frame looks like (we have two list_types: light and heavy): 
```
data.head()
        subject	list	item	       input   output	study	recall	repeat intrusion list_type category
0	1	1	Halle Berry	1.0	1.0	True	True	0	False	light	cel
1	1	1	Simon Cowell	2.0	3.0	True	True	0	False	light	cel
2	1	1	Kristen Stewart	3.0	4.0	True	True	0	False	light	cel
3	1	1	highlighter	4.0	8.0	True	True	0	False	light	obj
4	1	1	acorn      	5.0	NaN	True	False	0	False	light	obj
```
and I can successfully use the `fr.lag_crp` method to create df specific to the list_type. 
```python
light = data.loc[data['list_type'] == 'light']
crp_light = fr.lag_crp(light)

heavy = data.loc[data['list_type'] == 'heavy']
crp_heavy = fr.lag_crp(heavy)
```
This way, I can use crp_light and crp_heavy to plot each list_type's condition, but am having some trouble overlaying the two. I was wondering if you had any immediate thought/advice on approaching this problem as I wasn't fully familiar with the `item_query` argument description in the `lag_crp`. Thank you!

**Comment by mortonne** [comment]
This is one area the package could use more documentation on. You can use the pandas DataFrame methods `groupby` and `apply` to run an analysis on multiple conditions:

```python
crp = data.groupby('list_type').apply(fr.lag_crp)
```

Now you have separate CRPs for each list type, all within the `crp` DataFrame. For this to run correctly, all recalls in each list, including intrusions, should have the list type column defined so that recall sequences are not broken up by the groupby command.

Then, `fr.plot_lag_crp` takes optional inputs for splitting things out different ways, including the `hue` option to plot multiple curves on one axis. The plotting function returns a Seaborn grid object, which has an `add_legend` method that we can call to label the different colors.

```python
fr.plot_lag_crp(crp, hue='list_type').add_legend()
```

The `hue`, `col`, and `row` Seaborn flags can be combined however you want. For example, you could make a plot for each participant with different colors for each condition with something like this:

```python
fr.plot_lag_crp(crp, hue='list_type', col='subject', col_wrap=5).add_legend()
```

**Comment by mortonne** [comment]
See also the new documentation page on [Comparing conditions](https://psifr.readthedocs.io/en/latest/guide/grouping.html).

**Comment by jeon11** [comment]
Worked like a charm! I should've referred to how you split the list_type in the spc example. I was just somehow stuck with this for so long. Thank you, and great documentation too!
![beh_crps](https://user-images.githubusercontent.com/17741478/85375012-48d60d00-b4fb-11ea-884f-58242ca49257.jpg)
